package JavaDemoTest;


import java.util.Scanner;

public class Random_Number_Guess_12
        {
         //java main method
        public static void main(String [] args )
        {
           double randomDouble = Math.random();
           randomDouble = randomDouble* 50 + 1;
           int randomInt = (int) randomDouble;
           //random number is shown so that user can check how program is working
           System.out.println("Random number generated by system is : " +randomInt);

           Scanner scanner = new Scanner(System.in);
           int num = scanner.nextInt();
           //if random number is not same as user entered number,go in while loop
                while (num != randomInt)
                {
                   if (num>randomInt)
                   {
                           System.out.println("Number is same");
                   }

                }
        }
        }
